version: "3.8"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: traveli-web-front
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./front:/home/app
      - node_modules_volume:/home/app/node_modules:delegated
      - build_volume:/home/app/build:nocopy

volumes:
  node_modules_volume:
  build_volume: